# Standardization

Standardization rescales data so it has a mean of 0 and a standard deviation of 1. 

It does not bind values to a fixed range.

Formula: $$x_{\text{new}} = \frac{x - \mu}{\sigma}$$

Key Characteristic: Preserves outliers and works best when the data follows a Normal (Gaussian) distribution.

Common Use Cases: Algorithms that assume normally distributed data or rely on distance/variance (e.g., Logistic Regression, Support Vector Machines, Principal Component Analysis).

In [1]:
import pandas as pd
df = pd.read_csv('500hits.csv', encoding='latin-1')

In [2]:
df = df.drop(columns=['PLAYER', 'CS'])

In [3]:
df.describe().round(2)

,YRS,G,AB,R,H,2B,3B,HR,RBI,BB,SO,SB,BA,HOF
count,465.00,465.00,465.00,465.00,465.00,465.00,465.00,465.00,465.00,465.00,465.00,465.00,465.00,465.00
mean,17.05,2048.70,7511.46,1150.31,2170.25,380.95,78.55,201.05,894.26,783.56,847.47,195.91,0.29,0.33
std,2.77,354.39,1294.07,289.64,424.19,96.48,49.36,143.62,486.19,327.43,489.22,181.85,0.02,0.47
min,11.00,1331.00,4981.00,601.00,1660.00,177.00,3.00,9.00,0.00,239.00,0.00,7.00,0.25,0.00
25%,15.00,1802.00,6523.00,936.00,1838.00,312.00,41.00,79.00,640.00,535.00,436.00,63.00,0.27,0.00
50%,17.00,1993.00,7241.00,1104.00,2076.00,366.00,67.00,178.00,968.00,736.00,825.00,137.00,0.29,0.00
75%,19.00,2247.00,8180.00,1296.00,2375.00,436.00,107.00,292.00,1206.00,955.00,1226.00,285.00,0.30,1.00
max,26.00,3308.00,12364.00,2295.00,4189.00,792.00,309.00,755.00,2297.00,2190.00,2597.00,1406.00,0.37,2.00

In [4]:
X1 = df.iloc[:, 0:13].values
X2 = df.iloc[:, 0:13].values

In [5]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X1 = scaler.fit_transform(X1)

In [6]:
X1

array([[ 2.51629465,  2.78607833,  3.03444238, ..., -1.00362803,
         3.8320671 ,  3.64828983],
       [ 1.79223709,  2.76065536,  2.67704362, ..., -0.30994803,
        -0.64908031,  1.99615936],
       [ 1.79223709,  2.09118375,  2.0759639 , ..., -1.28396478,
         1.29972336,  2.65701155],
       ...,
       [-0.74196436, -0.60647609, -0.78322616, ...,  0.7009013 ,
         0.65562723, -1.54412022],
       [-0.37993558, -0.64037339, -0.93020833, ..., -0.73352254,
        -0.67110069, -1.21369413],
       [-0.74196436, -1.64034363, -1.45624979, ..., -0.77035511,
         0.39138266,  0.29682516]])

In [7]:
X1 = pd.DataFrame(X1, columns=['YRS','G','AB','R','H','2B','3B'	,'HR','RBI','BB','SO','SB', 'BA'])

In [8]:
X1.head()

,YRS,G,AB,R,H,2B,3B,HR,RBI,BB,SO,SB,BA
0,2.516295,2.786078,3.034442,3.787062,4.764193,3.559333,4.389485,-0.585841,-0.346449,1.423013,-1.003628,3.832067,3.648290
1,1.792237,2.760655,2.677044,2.760530,3.444971,3.569709,1.996457,1.909487,2.175837,2.493089,-0.309948,-0.649080,1.996159
2,1.792237,2.091184,2.075964,2.528955,3.171214,4.264876,2.909053,-0.585841,-0.350567,1.826585,-1.283965,1.299723,2.657012
3,1.068180,1.972543,2.849554,2.670665,3.055576,1.691719,-0.254611,0.410896,0.858071,0.912434,2.030966,0.892346,1.004881
4,1.430208,2.099658,2.257758,2.024329,2.972977,2.687780,3.517449,-0.697364,-1.841290,0.548609,-1.065016,2.896201,1.901752

In [9]:
X1.describe().round(3)

,YRS,G,AB,R,H,2B,3B,HR,RBI,BB,SO,SB,BA
count,465.000,465.000,465.000,465.000,465.000,465.000,465.000,465.000,465.000,465.000,465.000,465.000,465.000
mean,-0.000,0.000,0.000,0.000,0.000,0.000,-0.000,-0.000,0.000,0.000,-0.000,0.000,0.000
std,1.001,1.001,1.001,1.001,1.001,1.001,1.001,1.001,1.001,1.001,1.001,1.001,1.001
min,-2.190,-2.027,-1.958,-1.899,-1.204,-2.116,-1.532,-1.339,-1.841,-1.665,-1.734,-1.040,-2.016
25%,-0.742,-0.697,-0.765,-0.741,-0.784,-0.715,-0.762,-0.851,-0.524,-0.760,-0.842,-0.732,-0.742
50%,-0.018,-0.157,-0.209,-0.160,-0.222,-0.155,-0.234,-0.161,0.152,-0.145,-0.046,-0.324,-0.081
75%,0.706,0.560,0.517,0.504,0.483,0.571,0.577,0.634,0.642,0.524,0.775,0.490,0.533
max,3.240,3.557,3.754,3.956,4.764,4.265,4.673,3.861,2.888,4.300,3.580,6.662,3.648

# Normalization

Normalization rescales data so that all values fit strictly within a fixed range, typically[0, 1]

Formula: $$x_{\text{new}} = \frac{x - x_{\text{min}}}{x_{\text{max}} - x_{\text{min}}}$$

Key Characteristic: Highly sensitive to outliers, as extreme values compress the normal data into a tiny range.

Common Use Cases: Algorithms that do not assume any specific distribution or require bounded inputs (e.g., K-Nearest Neighbors, Neural Networks, Image Processing pixel values).

In [10]:
from sklearn.preprocessing import MinMaxScaler

In [11]:
scaleMinMax = MinMaxScaler(feature_range=(0,1))

In [12]:
X2 = scaleMinMax.fit_transform(X2)

X2 = pd.DataFrame(X2, columns=['YRS','G','AB','R','H','2B','3B'	,'HR','RBI','BB','SO','SB', 'BA'])

In [13]:
X2.describe().round(3)

,YRS,G,AB,R,H,2B,3B,HR,RBI,BB,SO,SB,BA
count,465.000,465.000,465.000,465.000,465.000,465.000,465.000,465.000,465.000,465.000,465.000,465.000,465.000
mean,0.403,0.363,0.343,0.324,0.202,0.332,0.247,0.257,0.389,0.279,0.326,0.135,0.356
std,0.184,0.179,0.175,0.171,0.168,0.157,0.161,0.193,0.212,0.168,0.188,0.130,0.177
min,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
25%,0.267,0.238,0.209,0.198,0.070,0.220,0.124,0.094,0.279,0.152,0.168,0.040,0.225
50%,0.400,0.335,0.306,0.297,0.164,0.307,0.209,0.227,0.421,0.255,0.318,0.093,0.342
75%,0.533,0.463,0.433,0.410,0.283,0.421,0.340,0.379,0.525,0.367,0.472,0.199,0.450
max,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000