In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('2022mlbteams.csv')

df.head()

,Tm,Bat,BatAge,R/G,G,PA,AB,R,H,2B,...,SLG,OPS,OPS+,TB,GDP,HBP,SH,SF,IBB,LOB
0,Arizona Diamondbacks,57,26.5,4.33,162,6027,5351,702,1232,262,...,0.385,0.689,95,2061,97,60,31,50,14,1039
1,Atlanta Braves,53,27.5,4.87,162,6082,5509,789,1394,298,...,0.443,0.761,109,2443,103,66,1,36,13,1030
2,Baltimore Orioles,58,27.0,4.16,162,6049,5429,674,1281,275,...,0.390,0.695,99,2119,95,83,12,43,10,1095
3,Boston Red Sox,54,28.8,4.54,162,6144,5539,735,1427,352,...,0.409,0.731,102,2268,131,63,12,50,23,1133
4,Chicago Cubs,64,27.9,4.06,162,6072,5425,657,1293,265,...,0.387,0.698,94,2097,130,84,19,36,16,1100

In [4]:
df.drop('Tm', axis=1, inplace=True)

df.head()

,Bat,BatAge,R/G,G,PA,AB,R,H,2B,3B,...,SLG,OPS,OPS+,TB,GDP,HBP,SH,SF,IBB,LOB
0,57,26.5,4.33,162,6027,5351,702,1232,262,24,...,0.385,0.689,95,2061,97,60,31,50,14,1039
1,53,27.5,4.87,162,6082,5509,789,1394,298,11,...,0.443,0.761,109,2443,103,66,1,36,13,1030
2,58,27.0,4.16,162,6049,5429,674,1281,275,25,...,0.390,0.695,99,2119,95,83,12,43,10,1095
3,54,28.8,4.54,162,6144,5539,735,1427,352,12,...,0.409,0.731,102,2268,131,63,12,50,23,1133
4,64,27.9,4.06,162,6072,5425,657,1293,265,31,...,0.387,0.698,94,2097,130,84,19,36,16,1100

In [5]:
X = df.iloc[:,0:27]
y = df.iloc[:,27]

In [6]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=21)

In [7]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

In [8]:
X_train = scaler.fit_transform(X_train)
X_train = pd.DataFrame(X_train, columns=['Bat', 'BatAge', 'R/G', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR',
       'RBI', 'SB', 'CS', 'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB',
       'GDP', 'HBP', 'SH', 'SF', 'IBB'])

In [9]:
X_train.describe().round(3)

,Bat,BatAge,R/G,G,PA,AB,R,H,2B,3B,...,OBP,SLG,OPS,OPS+,TB,GDP,HBP,SH,SF,IBB
count,25.000,25.000,25.000,25.000,25.000,25.000,25.000,25.000,25.000,25.000,...,25.000,25.000,25.000,25.000,25.000,25.000,25.000,25.000,25.000,25.000
mean,0.000,0.000,0.000,0.000,0.000,0.000,-0.000,0.000,-0.000,-0.000,...,-0.000,-0.000,-0.000,0.000,0.000,0.000,0.000,0.000,0.000,-0.000
std,1.021,1.021,1.021,1.021,1.021,1.021,1.021,1.021,1.021,1.021,...,1.021,1.021,1.021,1.021,1.021,1.021,1.021,1.021,1.021,1.021
min,-0.251,-2.223,-1.993,-0.204,-0.210,-0.208,-0.237,-0.228,-0.234,-0.313,...,-2.494,-2.021,-2.288,-1.854,-0.230,-0.257,-0.259,-0.360,-0.268,-0.312
25%,-0.215,-0.708,-0.616,-0.204,-0.206,-0.205,-0.214,-0.211,-0.215,-0.240,...,-0.475,-0.603,-0.524,-0.671,-0.211,-0.216,-0.230,-0.252,-0.221,-0.268
50%,-0.208,-0.045,0.122,-0.204,-0.204,-0.205,-0.202,-0.204,-0.203,-0.215,...,0.114,0.023,-0.003,0.082,-0.204,-0.201,-0.217,-0.212,-0.200,-0.235
75%,-0.187,0.806,0.712,-0.204,-0.202,-0.203,-0.192,-0.195,-0.193,-0.141,...,0.535,0.608,0.748,0.619,-0.194,-0.182,-0.171,-0.104,-0.187,-0.124
max,4.898,1.848,1.794,4.899,4.899,4.899,4.898,4.899,4.898,4.889,...,1.798,2.026,1.616,1.910,4.899,4.898,4.895,4.882,4.897,4.878

In [10]:
from sklearn.decomposition import PCA

pca = PCA()

In [11]:
X_pca = pca.fit_transform(X_train)

In [12]:
pca.explained_variance_ratio_

array([7.39815070e-01, 1.95691967e-01, 4.00548033e-02, 1.37221252e-02,
       5.44617277e-03, 3.11057090e-03, 1.50892303e-03, 3.03755509e-04,
       1.06565150e-04, 9.35108441e-05, 7.07541045e-05, 2.69420825e-05,
       2.20182500e-05, 9.74493519e-06, 7.25634243e-06, 6.22161121e-06,
       2.19262066e-06, 9.03548456e-07, 4.62710020e-07, 2.19684349e-08,
       1.04343652e-08, 6.80361424e-09, 2.40449600e-10, 3.49127794e-11,
       1.61752543e-34])

In [15]:
pca2 = PCA(0.95)

X_pca2 = pca2.fit_transform(X_train)

In [16]:
X_pca2.shape

(25, 3)

In [17]:
pca3 = PCA(n_components=2)

X_pca3 = pca3.fit_transform(X_train)

In [18]:
X_pca3.shape

(25, 2)